debug_mode: false
data:
  data_loader_name: "JSONLoader"
  user_loader_name: "UserTsvLoader"
  data_path: "data/ml25M_100_movie_sample.json"
  user_path: "data/users/movielens_100_50_users.tsv"
dialogue_sim:
  num_turns: 10
  sim_type: "llm" # options: "llm" "manual"
llm:
  model: "gpt-3.5-turbo-1106" # options: "gpt-3.5-turbo" "gpt-3.5-turbo-instruct" "text-davinci-003"
  llm_name: 'GPTChatCompletion'
  like_probs_template: "pref_query.jinja2"
  user_sim_template_file: "user_simulation_movie.jinja2"
  template_dir: "./templates"
  temperature: 0
  entailement_model: "cross-encoder/ms-marco-MiniLM-L-12-v2"
logging:
  disabled: False # Replace with false
  level: DEBUG # options: INFO, DEBUG, WARNING
mono_llm:
  query_gen_template: "mono_llm_query_gen.jinja2"
  top_items_template: "mono_llm_top_items.jinja2"
pe:
  pe_module_name: "DT" # options: "MonoLLM", "DT"
  response_update: "individual" # options: "individual", "concatenated" -> Use most recent response or all responses for the update
  num_recs: 10
query:
  aspect_gen_template: "pointwise_aspect_v_generation_movies_3FS.jinja2"
  aspect_extraction: "val"
  query_gen_template: "pointwise_query_generation.jinja2"
  item_selection: "greedy" # Which item selection method to use. See map in query_selection.pointwise_item_selection
item_scoring:
  item_scorer_name: "MNLIScorer" #options: "EntailmentScorer","CEScorer","DenseRetrievalScorer" "LLMLogprobScorer" "MNLIScorer"
  mnli_model: "facebook/bart-large-mnli"
  preprocess_query: True
  history_preprocessor_name: "AspectValuePreprocessor" # options "AspectKVPreprocessor" "HistoryConcatenator"
  mnli_temp: 1
# Beginning of Evaluation Management Parameters #######################
ci:
  confidence_level: 0.95
metrics:
  metrics: supported_measures
  to_avg:
    map: null
paths:
  experiment_dir: experiments/david_test_1
  eval_results_master_path: experiments/david_test_1/eval_results.csv
