debug_mode: false  
data:
  data_loader_name: "JSONLoader"
  data_path: "data/shapes.json"
  user_path: "data/users/single_user.json"
dialogue_sim:
  num_recs: 1
  num_turns: 3
  sim_type: "llm" # options: "llm" "manual"
llm:
  model: "gpt-3.5-turbo-instruct" # options: "gpt-3.5-turbo" "text-davinci-003"
  llm_name: 'GPTCompletion'
  like_probs_template: "pref_query.jinja2"
  user_sim_template_file: "user_simulation.jinja2"
  temperature: 0.2
logging:
  disabled: False # Replace with false
  level: DEBUG # options: INFO, DEBUG, WARNING
mono_llm:
  query_gen_template: "mono_llm_query_gen.jinja2"
  top_items_template: "mono_llm_top_items.jinja2"
pe:
  pe_module_name: "DT" # options: "MonoLLM", "DT"
  response_update: "individual" # options: "individual", "concatenated" -> Use most recent response or all responses for the update
query:
  query_gen_template: "pointwise_query_generation.jinja2"
  item_selection: "greedy" # Which item selection method to use. See map in query_selection.pointwise_item_selection