debug_mode: false
data:
  data_loader_name: "JSONLoader"
  user_loader_name: "UserTsvLoader"
  data_path: "data/yelp_cat_1000.json"
  user_path: "data/users/users_10_1000.tsv"
dialogue_sim:
  num_turns: 10
  sim_type: "llm" # options: "llm" "manual"
  response_noise: 0
llm:
  model: "gpt-3.5-turbo-0613" # options: "gpt-3.5-turbo" "gpt-3.5-turbo-instruct" "text-davinci-003"
  llm_name: 'GPTChatCompletion'
  like_probs_template: "pref_query.jinja2"
  user_sim_template_file: "user_simulation_1000_restaurants.jinja2"
  template_dir: "./templates"
  temperature: 0
  entailement_model: "cross-encoder/ms-marco-MiniLM-L-12-v2"
logging:
  disabled: False # Replace with false
  level: DEBUG # options: INFO, DEBUG, WARNING
pe:
  pe_module_name: "DT" # options: "MonoLLM", "DT"
  response_update: "individual" # options: "individual", "concatenated" -> Use most recent response or all responses for the update
  num_recs: 10
  setup: "pointwise"
query:
  aspect_gen_template: "pointwise_aspect_v_generation_1000_restaurants_3FS_3words.jinja2"
  aspect_extraction: "val"
  query_gen_template: "pointwise_query_generation_v.jinja2"
  item_selection: "ucb" # Which item selection method to use. See map in query_selection.pointwise_item_selection
item_scoring:
  item_scorer_name: "MNLIScorer" #options: "EntailmentScorer","CEScorer","DenseRetrievalScorer" "LLMLogprobScorer" "MNLIScorer"
  mnli_model: "facebook/bart-large-mnli"
  preprocess_query: True
  history_preprocessor_name: "AspectValuePreprocessor" # options "AspectKVPreprocessor" "HistoryConcatenator"
  mnli_temp: 100
  batch_size: 100
# Beginning of Evaluation Management Parameters #######################
ci:
  confidence_level: 0.95
metrics:
  metrics: supported_measures
  to_avg:
    map: null
paths:
  experiment_dir: experiments/david_test_1
  eval_results_master_path: experiments/david_test_1/eval_results.csv
